---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/sabnzbd:/config
      - ./data/usenet:/data/usenet
    ports:
      - 8080:8080
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/sonarr:/config
      - ./data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/radarr:/config
      - ./data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  readarr:
    container_name: readarr
    image: linuxserver/readarr:develop
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/readarr:/config
      - ./data:/data
    ports:
      - "8787:8787"
    restart: unless-stopped

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/lidarr:/config
      - ./data:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/jellyfin:/config
      - ./data/media:/data/media
    ports:
      - "8096:8096"
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    ports:
      - "7575:7575"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./appdata/homarr/configs:/app/data/configs
      - ./appdata/homarr/icons:/app/public/icons
      - ./appdata/homarr/data:/data
    restart: unless-stopped

  kgcf-rsync:
    container_name: kgcf-rsync
    image: cvdg/kgcf-rsync
    build:
      context: rsync
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    ports:
      - "9873:9873"
    volumes:
      - ./data/media:/data/media
    restart: unless-stopped
