---
version: "3"
services:
  # .env:
  #   - OPENVPN_USER
  #   - OPENVPN_PASSWORD
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8096:8096 # jellyfin
      - 8989:8989 # sonarr
      - 9091:9091 # transmission
      - 9696:9696 # prowlar

      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      # - 8888:8888/tcp # HTTP proxy
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Netherlands
      - UPDATER_PERIOD="24h"
    volumes:
      - /appdata/gluetun:/gluetun
      - /data:/data

    # ports:
    #   - 9091:9091
    #   - 51413:51413
    #   - 51413:51413/udp
    # .env:
    #   - TRANSMISSION_USER
    #   - TRANSMISSION_PASSWORD
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - /appdata/transmission:/config
      - /data:/data

  # ports:
  #   - 9696:9696
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /appdata/prowlarr:/config

  # ports:
  #   - "8989:8989"
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /appdata/sonarr:/config
      - /data:/data

  #  ports:
  #    - "8096:8096"
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /appdata/jellyfin:/config
      - /data:/data
